[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algonaut = "0.4.1"
base32 = "0.4.0"
ocl = { version = "0.19.4" }
rand = "0.8.5"
ring = "0.16.20"
sha2 = "0.10.6"
